### ISSUE TITLE
Duplicate content being posted

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1070]
We are seeing a lot of duplicate postings on GCconnex, mostly affecting the opportunities platform. See attached image of digest received, with items being repeated up to 18 times in the digest. We need to stress the importance of investigating and fixing these issues urgently.

This is tremendously frustrating for users.
![duplicate postings](https://cloud.githubusercontent.com/assets/15378977/25899421/c96bb3aa-355d-11e7-9f22-7d281ee75a72.JPG)

**Comment by LemieuxGen** [comment]
@cdegrass @Phanoix @pandurx @Troy-Lawson As per @ToferC email from this morning, could we please look at this urgently. Thanks.

**Comment by Phanoix** [comment]
It's still happening after last update?

**Comment by LemieuxGen** [comment]
Yes, the example is from this morning (so content posted yesterday).

**Comment by Phanoix** [comment]
OK, I'm assuming if you check the opportunities platform you will actually see that many duplicate opportunities?

**Comment by LemieuxGen** [comment]
Yes, see attached image.
![duplicate postings_op](https://cloud.githubusercontent.com/assets/15378977/25900482/9e01b0b2-3561-11e7-97dd-a3ef94ae439e.JPG)

**Comment by Phanoix** [comment]
So the notifications are working properly, we're just getting many duplicate posts, each triggering a notification...  a big part of this is probably our server load issues, but I'll see if there's something that can be done with what we have.

**Comment by Troy-Lawson** [comment]
This is not a new issue. This is the same issue i spoke to during sprint planning. we are hoping adding emergency ram to the database will positively effect the issue.

**Comment by LemieuxGen** [comment]
I would say that yes, the notifications are working properly. However, could it have anything to do with the issue brought up by Troy and Christine, related to the content being saved in queue for the digest, exceeding the maximum number of characters?

**Comment by Phanoix** [comment]
Do we know for sure if these duplicates are the result of the users submitting / saving their posts once and getting 4/5+ extra or do they get an error and attempt to re-submit?

**Comment by Troy-Lawson** [comment]
we cant know for sure, but i find it unlikely a user attempt to post something 14+ times manually before realising the first was successful

**Comment by Phanoix** [comment]
True, most are probably from one or 2 attempts to post especially after we implemented some countermeasures against multiple submit clicks last update. As long as the duplicates aren't a completely database-side phenomenon there might be some countermeasures we can put in place though...

**Comment by klecuyer** [comment]
Okay how do I merge these two issues #1267 ? @Phanoix  I apologize I didn't see this was still open. Just got a second inquiry from a user about the same issue. +2

**Comment by Phanoix** [comment]
I'll just mark that one as a duplicate and close it.

**Comment by klecuyer** [comment]
Confirm that this is still happening for users when posting a new Group Discussion. Happening in one group, but only to one user when posting, sometimes 2 or 3 times. Other users are not having the same duplicate issue.

Group: https://gcconnex.gc.ca/discussion/owner/17164879

User: https://gcconnex.gc.ca/profile/Andreane.Cossette

**Comment by Phanoix** [comment]
Opportunity duplicates should no longer happen. #1370

**Comment by KevinChagnon** [comment]
could it happen to be the fact that any of her duplicate posts seem to be when she posts content in both languages? That doesn’t happen for me but like you said it doesn’t seem to happen to all users.

**Comment by klecuyer** [comment]
Multiple users reporting duplicate emails/notifications for blogs, events, and polls. My guess is that this is related to slow network connectivity and it re-posting/reloading. I remember there being a fix put in for the Draft feature, but not all of these feature use Draft, like polls and events, so it must be something else. Sometimes I'm sure this can be attributed to user error, but not always. I should clarify, this is not just duplicate notifications, but duplicate posts also. Some examples:
![image](https://user-images.githubusercontent.com/29754185/39374475-f6b5d338-4a18-11e8-8a55-b3b1a55800f3.png)
![image](https://user-images.githubusercontent.com/29754185/39374768-026d3422-4a1a-11e8-8df5-2129a1ab4285.png)
https://gcconnex.gc.ca/blog/group/19651377/all
![image](https://user-images.githubusercontent.com/29754185/39374798-2531a2b8-4a1a-11e8-81d2-fd294ba46e4e.png)
https://gcconnex.gc.ca/polls/group/4506076/all
(has since been deleted, but I did see it here): https://gcconnex.gc.ca/event_calendar/group/4485836

**Comment by klecuyer** [comment]
Linked to: https://github.com/gctools-outilsgc/gcconnex/issues/1414

**Comment by klecuyer** [comment]
Closing to keep one ticket #1414

**Comment by klecuyer** [comment]
Assume this is different from the notification issues here #1414 
This is likely related to network connectivity. The page loads and loads, errors out, then posts the content multiple times.
![image](https://user-images.githubusercontent.com/29754185/43597947-86cd6baa-9651-11e8-96a5-e55da639925f.png)

**Comment by Phanoix** [comment]
What content types are stiff getting duplicates? I can try adding them to the duplication countermeasure I have set up that seems to have been working so far for a few types.

**Comment by klecuyer** [comment]
@Phanoix it seems to be a mix of blogs, discussions, and polls

**Comment by Phanoix** [comment]
For discussions is it new discussions being started or replies or both?

**Comment by klecuyer** [comment]
I would say the trend seems to be new content (discussions)

**Comment by Phanoix** [comment]
Are blogs still getting duplicated? That should have been fixed / prevented from happening about a month ago.

**Comment by marc-donofrio** [comment]
No longer an issue.
